FROM node:18-alpine
WORKDIR /app
COPY server/package*.json ./
RUN npm ci --only=production
COPY server/ ./
RUN mkdir -p /app/logs && chmod -R 777 /app/logs
RUN mkdir -p uploads
EXPOSE 5000
USER node
CMD ["node", "src/index.js"]
