const ROLES = Object.freeze({
  STUDENT: 'STUDENT',
  COMPANY: 'COMPANY',
  ADMIN: 'ADMIN',
  PLACEMENT_OFFICER: 'PLACEMENT_OFFICER',
});

const APPLICATION_STATUS = Object.freeze({
  APPLIED: 'APPLIED',
  SHORTLISTED: 'SHORTLISTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SELECTED: 'SELECTED',
  REJECTED: 'REJECTED',
  ON_HOLD: 'ON_HOLD',
});

const JOB_TYPES = Object.freeze({
  FULL_TIME: 'FULL_TIME',
  INTERNSHIP: 'INTERNSHIP',
  BOTH: 'BOTH',
});

const NOTIFICATION_TYPES = Object.freeze({
  APPLICATION_UPDATE: 'APPLICATION_UPDATE',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  DRIVE_ANNOUNCEMENT: 'DRIVE_ANNOUNCEMENT',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
});

module.exports = {
  ROLES,
  APPLICATION_STATUS,
  JOB_TYPES,
  NOTIFICATION_TYPES,
};
